"use client";
import rosetta from "rosetta";

const i18n = rosetta({
  es: {
    shared: {
      title: "tusiguientecasa.com",
      start: "Comenzar",
    },
    landing: {
      title: "Encuentra tu siguiente mejor",
      highlight: "inversión",
    },
    types: {
      title: "Tipos de Inversión",
      industrial: "Nave Industrial",
      plaza: "Plaza Comercial",
      house: "Casa Residencial",
    },
    housing: {
      from: "desde",
      add: "Agregar Propiedad",
      addNew: "Agregar Nueva Propiedad",
      addSuccess: "Propiedad agregada exitosamente",
      addError: "Error al agregar la propiedad",
      name: "Nombre",
      namePlaceholder: "Ingresa el nombre de la propiedad",
      price: "Precio",
      pricePlaceholder: "Ingresa el precio",
      percentage: "Porcentaje",
      percentagePlaceholder: "Ingresa el porcentaje de rendimiento",
      state: "Estado",
      statePlaceholder: "Selecciona un estado",
      municipality: "Municipio",
      municipalityPlaceholder: "Selecciona un municipio",
      selectStateFirst: "Primero selecciona un estado",
      type: "Tipo",
      typePlaceholder: "Selecciona un tipo",
      latitude: "Latitud",
      latitudePlaceholder: "Ingresa la latitud",
      longitude: "Longitud",
      longitudePlaceholder: "Ingresa la longitud",
      coordinates: "Coordenadas",
      tag: "Etiqueta",
      tagPlaceholder: "Ingresa una etiqueta única",
      tagAutoGenerated: "Generada automáticamente basada en la selección de ubicación",
      images: "Imágenes",
      uploadImages: "Subir Imágenes",
      uploadInstructions: "Haz clic para seleccionar imágenes o arrastra y suelta",
      uploadSuccess: "Imágenes subidas exitosamente",
      uploadError: "Error al subir imágenes",
      noImagesUploaded: "No se han subido imágenes",
      url: "URL",
      urlPlaceholder: "Ingresa la URL",
      cancel: "Cancelar",
      save: "Guardar",
      required: "Campo requerido",
      invalidCoordinates: "Coordenadas inválidas",
      centerMap: "Centrar",
      mapPickerInstructions: "Haz clic en el mapa o arrastra el marcador para seleccionar las coordenadas",
    },
  },
  en: {
    shared: {
      title: "tusiguientecasa.com",
      start: "Start",
    },
    landing: {
      title: "Find your next best",
      highlight: "investment",
    },
    types: {
      title: "Investment Types",
      industrial: "Industrial Warehouse",
      plaza: "Commercial Plaza",
      house: "Residential House",
    },
    housing: {
      from: "from",
      add: "Add Property",
      addNew: "Add New Property",
      addSuccess: "Property added successfully",
      addError: "Error adding property",
      name: "Name",
      namePlaceholder: "Enter property name",
      price: "Price",
      pricePlaceholder: "Enter price",
      percentage: "Percentage",
      percentagePlaceholder: "Enter yield percentage",
      state: "State",
      statePlaceholder: "Select a state",
      municipality: "Municipality",
      municipalityPlaceholder: "Select a municipality",
      selectStateFirst: "Please select a state first",
      type: "Type",
      typePlaceholder: "Select a type",
      latitude: "Latitude",
      latitudePlaceholder: "Enter latitude",
      longitude: "Longitude",
      longitudePlaceholder: "Enter longitude",
      coordinates: "Coordinates",
      tag: "Tag",
      tagPlaceholder: "Enter a unique tag",
      tagAutoGenerated: "Auto-generated based on location selection",
      images: "Images",
      uploadImages: "Upload Images",
      uploadInstructions: "Click to select images or drag and drop",
      uploadSuccess: "Images uploaded successfully",
      uploadError: "Error uploading images",
      noImagesUploaded: "No images uploaded",
      url: "URL",
      urlPlaceholder: "Enter URL",
      cancel: "Cancel",
      save: "Save",
      required: "Required field",
      invalidCoordinates: "Invalid coordinates",
      centerMap: "Center",
      mapPickerInstructions: "Click on the map or drag the marker to select coordinates",
    },
  },
});

export const TranslationService = {
  init: function () {
    let myLocale;
    if (typeof window !== "undefined")
      myLocale = localStorage.getItem("locale");
    myLocale = myLocale || "es";
    i18n.locale(myLocale);
  },
  t: i18n.t,
  setLocale: (locale) => {
    if (typeof window !== "undefined") localStorage.setItem("locale", locale);
    window.location.reload();
  },
  getLocale: () => i18n.locale(),
};
